{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: apps/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Deployment
metadata:
  name: {{ include "courier.name" . }}
  labels:
    {{- include "courier.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "courier.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "courier.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "courier.serviceAccountName" . }}
      containers:
      {{- $image := .Values.image.repository }}
      {{- $imageTag := .Values.image.tag }}
      {{- $pullPolicy := .Values.image.pullPolicy }}
      {{- range .Values.containers }}
      - name: {{ .name }}
        image: "{{ .image | default $image }}:{{ .imageTag | default $imageTag }}"
        imagePullPolicy: {{ .imagePullPolicy | default $pullPolicy }}
        {{- with .command }}
        command:
          {{- toYaml . | nindent 8 }}
        {{- end }}  
        {{- with .envFrom }}
        envFrom:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .env }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .ports }}
        ports:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .resources }}
        resources:
          {{- toYaml . | nindent  }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
