{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "courier.name" . }}
  labels:
    {{- include "courier.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
    {{- include "courier.selectorLabels" . | nindent 4 }}
{{- end }}
