pipeline {
  agent {
    kubernetes {
      label 'jenkins-slaves'
      defaultContainer 'jnlp'
    }
  }
  stages {

    stage('Build Image') {
      steps {
        container('docker') {
          //BUILD DOCKER
          dir("demo") {
            sh "until docker ps; do sleep 3; done"
            sh "docker build -t ${REGISTRY}/${PROJECT}/${$SERVICE}:${ENV}-${GIT_COMMIT} ."
            sh "docker tag ${REGISTRY}/${PROJECT}/${SERVICE}:${ENV}-${GIT_COMMIT} ${REGISTRY}/${PROJECT}/${SERVICE}:${TAG}"
          }
        }
      }
    }

    stage('Push Image') {
      steps {
        container('docker') {
          //PUSH DOCKER TO REGISTRY
          sh "docker push ${REGISTRY}/${PROJECT}/${SERVICE}:${ENV}-${GIT_COMMIT}"
          sh "docker push ${REGISTRY}/${PROJECT}/${SERVICE}:${TAG}"
          sh "docker rmi ${REGISTRY}/${PROJECT}/${SERVICE}:${ENV}-${GIT_COMMIT} && docker rmi ${REGISTRY}/${PROJECT}/${SERVICE}:${TAG}"
        }
      }
    }

    stage('Deploy E2E') {
      environment {
        GIT_CREDS = credentials('git')
      }
      steps {
        container('tools') {
          sh "git clone https://$GIT_CREDS_USR:$GIT_CREDS_PSW@github.com/lukyr/nick-fury.git"
          sh "git config --global user.email 'luky.ramdhanie@gmail.com'"

          dir("nick-fury") {
            sh "cd ./overlays/stg/lotus && helm template -f config.yaml  ../../../charts/courier > resources.yaml && kustomize edit set image 192.168.0.105:5000/lotus:${env.GIT_COMMIT}"
            sh "git commit -am 'Publish new version' && git push || echo 'no changes'"
          }
        }
      }
    }
  }
}
