apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources.yaml

configMapGenerator:
- name: lotus-env
  envs:
  - env.properties
  
images:
- name: nginx
  newTag: latest