apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources.yaml

configMapGenerator:
- envs:
  - env.properties
  name: lotus-env
  
images:
- name: 192.168.0.105:5000/argocd-demo
  newTag: ac27aaf1db1e5517c73ae2e2c32a8f373f800b39
