apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources.yaml

configMapGenerator:
- envs:
  - env.properties
  name: lotus-env
  
images:
- name: 192.168.0.105:5000/argocd-demo
  newTag: 8944f2e32f740554adffb73c649c20aec8c93c34
