apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources.yaml

configMapGenerator:
- envs:
  - env.properties
  name: shiva-env
  
images:
- name: 192.168.0.105:5000/mbizmarket/shiva
  newTag: stg-4f5a6d1fbc3dd8217b6aa009bbc7a38900b8fe64
