---
# Source: courier/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: shiva
  labels:
    helm.sh/chart: courier-0.1.0
    app.kubernetes.io/name: shiva
    app.kubernetes.io/version: "1.17.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: shiva
---
# Source: courier/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiva
  labels:
    helm.sh/chart: courier-0.1.0
    app.kubernetes.io/name: shiva
    app.kubernetes.io/version: "1.17.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: shiva
  template:
    metadata:
      labels:
        app.kubernetes.io/name: shiva
    spec:
      serviceAccountName: default
      containers:
      - name: shiva
        image: "192.168.0.105:5000/mbizmarket/shiva:latest"
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: shiva-env
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
